spring:
  cloud:
    consul:
      config:
        format: YAML
      host: localhost
      port: 8500
  application:
    name: gateway
  config:
    import: optional:consul:localhost:8500
  profiles:
    active: dev


server:
  port: 10000